"""AI investigation endpoints."""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException

from app.dependencies import get_state
from app.schemas import InvestigationOut
from app.services.app_state import AppState
from app.services.serializers import investigation_out

router = APIRouter(prefix="/api", tags=["investigations"])


@router.get(
    "/campaigns/{campaign_id}/investigation",
    response_model=InvestigationOut,
    summary="AI investigation report",
    description=(
        "Grounded investigation report (FACT/INFERENCE/UNCERTAINTY findings with "
        "evidence IDs) generated by the deterministic investigator. The AI never "
        "executes containment."
    ),
)
def investigation(campaign_id: str,
                  state: AppState = Depends(get_state)) -> InvestigationOut:
    if state.find_assessment(campaign_id) is None:
        raise HTTPException(status_code=404, detail="Campaign not found")
    inv = state.investigation_for(campaign_id)
    if "error" in inv:
        raise HTTPException(status_code=500, detail=inv.get("detail", "unknown"))
    return investigation_out(campaign_id, inv)